package i5.las2peer.services.toDoList;

import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;

import com.fasterxml.jackson.core.JsonProcessingException;

import i5.las2peer.api.Service;
import i5.las2peer.restMapper.HttpResponse;
import i5.las2peer.restMapper.MediaType;
import i5.las2peer.restMapper.RESTMapper;
import i5.las2peer.restMapper.annotations.ContentParam;
import i5.las2peer.restMapper.annotations.Version;
import i5.las2peer.services.toDoList.database.DatabaseManager;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import io.swagger.jaxrs.Reader;
import io.swagger.models.Swagger;
import io.swagger.util.Json;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;


/**
 * 
 * ToDoList Microservice Sample
 * 
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 * 
 */
@Path("ToDoList")
@Version("0.1") // this annotation is used by the XML mapper
@Api
@SwaggerDefinition(
    info = @Info(title = "ToDoList Microservice Sample", version = "0.1",
        description = "A LAS2peer microservice generated by the CAE.",
        termsOfService = "none",
        contact = @Contact(name = "desared", email = "CAEAddress@gmail.com") ,
        license = @License(name = "BSD",
            url = "https://github.com/CAE-Community-Application-Editor/microservice-ToDoList-Microservice-Sample/blob/master/LICENSE.txt") ) )
public class ToDoList extends Service {


  /*
   * Database configuration
   */
  private String jdbcDriverClassName;
  private String jdbcLogin;
  private String jdbcPass;
  private String jdbcUrl;
  private String jdbcSchema;
  private DatabaseManager dbm;


  public ToDoList() {
    // read and set properties values
    setFieldValues();
    // instantiate a database manager to handle database connection pooling and credentials
    dbm = new DatabaseManager(jdbcDriverClassName, jdbcLogin, jdbcPass, jdbcUrl, jdbcSchema);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods.
  // //////////////////////////////////////////////////////////////////////////////////////


  /**
   * 
   * postList
   * 
   * @param listContent a String
   * 
   * @return HttpResponse
   * 
   */
  @POST
  @Path("/ ")
  @Produces(MediaType.TEXT_PLAIN)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_CREATED, message = "ListSent"),
       @ApiResponse(code = HttpURLConnection.HTTP_INTERNAL_ERROR, message = "internalError")
  })
  @ApiOperation(value = "postList", notes = "")
  public HttpResponse postList(@ContentParam String listContent) {
    // ListSent
    boolean ListSent_condition = true;
    if(ListSent_condition) {
      String listCreated = "Some String";
      HttpResponse ListSent = new HttpResponse(listCreated, HttpURLConnection.HTTP_CREATED);
      return ListSent;
    }
    // internalError
    boolean internalError_condition = true;
    if(internalError_condition) {
      String eror = "Some String";
      HttpResponse internalError = new HttpResponse(eror, HttpURLConnection.HTTP_INTERNAL_ERROR);
      return internalError;
    }
    return null;
  }


  /**
   * 
   * deleteList
   * 
   * @param DeleteContent a String
   * 
   * @return HttpResponse
   * 
   */
  @DELETE
  @Path("/")
  @Produces(MediaType.TEXT_PLAIN)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_NOT_FOUND, message = "ListNotFound"),
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "ListDeleted"),
       @ApiResponse(code = HttpURLConnection.HTTP_BAD_REQUEST, message = "BadList")
  })
  @ApiOperation(value = "deleteList", notes = "")
  public HttpResponse deleteList(@ContentParam String DeleteContent) {
    // ListNotFound
    boolean ListNotFound_condition = true;
    if(ListNotFound_condition) {
      String listNotFound = "Some String";
      HttpResponse ListNotFound = new HttpResponse(listNotFound, HttpURLConnection.HTTP_NOT_FOUND);
      return ListNotFound;
    }
    // ListDeleted
    boolean ListDeleted_condition = true;
    if(ListDeleted_condition) {
      String listRemoved = "Some String";
      HttpResponse ListDeleted = new HttpResponse(listRemoved, HttpURLConnection.HTTP_OK);
      return ListDeleted;
    }
    // BadList
    boolean BadList_condition = true;
    if(BadList_condition) {
      String badList = "Some String";
      HttpResponse BadList = new HttpResponse(badList, HttpURLConnection.HTTP_BAD_REQUEST);
      return BadList;
    }
    return null;
  }


  // //////////////////////////////////////////////////////////////////////////////////////
  // Methods required by the LAS2peer framework.
  // //////////////////////////////////////////////////////////////////////////////////////

  
  /**
   * 
   * This method is needed for every RESTful application in LAS2peer. Please don't change.
   * 
   * @return the mapping
   * 
   */
  public String getRESTMapping() {
    String result = "";
    try {
      result = RESTMapper.getMethodsAsXML(this.getClass());
    } catch (Exception e) {
      e.printStackTrace();
    }
    return result;
  }


  /**
   * 
   * Returns the API documentation of all annotated resources for purposes of Swagger documentation.
   * 
   * @return The resource's documentation
   * 
   */
  @GET
  @Path("/swagger.json")
  @Produces(MediaType.APPLICATION_JSON)
  public HttpResponse getSwaggerJSON() {
    Swagger swagger = new Reader(new Swagger()).read(this.getClass());
    if (swagger == null) {
      return new HttpResponse("Swagger API declaration not available!",
          HttpURLConnection.HTTP_NOT_FOUND);
    }
    try {
      return new HttpResponse(Json.mapper().writeValueAsString(swagger), HttpURLConnection.HTTP_OK);
    } catch (JsonProcessingException e) {
      e.printStackTrace();
      return new HttpResponse(e.getMessage(), HttpURLConnection.HTTP_INTERNAL_ERROR);
    }
  }

}
