package i5.las2peer.services.toDoList;

import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import i5.las2peer.p2p.LocalNode;
import i5.las2peer.p2p.ServiceNameVersion;
import i5.las2peer.restMapper.MediaType;
import i5.las2peer.restMapper.RESTMapper;
import i5.las2peer.restMapper.data.Pair;
import i5.las2peer.restMapper.tools.ValidationResult;
import i5.las2peer.restMapper.tools.XMLCheck;
import i5.las2peer.security.ServiceAgent;
import i5.las2peer.security.UserAgent;
import i5.las2peer.testing.MockAgentFactory;
import i5.las2peer.webConnector.WebConnector;
import i5.las2peer.webConnector.client.ClientResponse;
import i5.las2peer.webConnector.client.MiniClient;

import org.json.simple.JSONObject;
import org.json.simple.JSONValue;


/**
 * 
 * ToDoList Microservice Sample - Test Class
 * 
 * This class provides a basic testing framework for the microservice ToDoList Microservice Sample. It was
 * generated by the CAE (Community Application Framework).
 *
 */
public class ToDoListTest {

  private static final String HTTP_ADDRESS = "http://127.0.0.1";
  private static final int HTTP_PORT = WebConnector.DEFAULT_HTTP_PORT;

  private static LocalNode node;
  private static WebConnector connector;
  private static ByteArrayOutputStream logStream;

  private static UserAgent testAgent;
  private static final String testPass = "adamspass";
  
  // version does not matter in tests
  private static final ServiceNameVersion testTemplateService = new ServiceNameVersion(ToDoList.class.getCanonicalName(),"0.1");

  private static final String mainPath = "ToDoList";


  /**
   * 
   * Called before the tests start.
   * 
   * Sets up the node and initializes connector and users that can be used throughout the tests.
   * 
   * @throws Exception
   * 
   */
  @BeforeClass
  public static void startServer() throws Exception {
/*
    // start node
    node = LocalNode.newNode();
    node.storeAgent(MockAgentFactory.getAdam());
    node.launch();*/
	  node = LocalNode.newNode();
	    UserAgent agent = MockAgentFactory.getAdam();
	    agent.unlockPrivateKey(testPass);  // changed variable
	    node.storeAgent(agent);
	    node.launch();

	  
    ServiceAgent testService = ServiceAgent.createServiceAgent(testTemplateService, "a pass");
    testService.unlockPrivateKey("a pass");

    node.registerReceiver(testService);

    // start connector
    logStream = new ByteArrayOutputStream();

    connector = new WebConnector(true, HTTP_PORT, false, 1000);
    connector.setLogStream(new PrintStream(logStream));
    connector.start(node);
    Thread.sleep(1000); // wait a second for the connector to become ready
    testAgent = MockAgentFactory.getAdam();

    connector.updateServiceList();
    // avoid timing errors: wait for the repository manager to get all services before continuing
    try {
      System.out.println("waiting..");
      Thread.sleep(10000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

  }


  /**
   * 
   * Test for the postList method.
   * 
   */
  
  @Test
  public void testpostList() {
    MiniClient c = new MiniClient();
    c.setAddressPort(HTTP_ADDRESS, HTTP_PORT);
    try {
      String listContent = "caption_init";
      listContent += ';' + "message_init"; 
      c.setLogin(Long.toString(testAgent.getId()), testPass);
      @SuppressWarnings("unchecked")
      ClientResponse result = c.sendRequest("POST", mainPath + "/ ", listContent ,
        MediaType.TEXT_PLAIN, MediaType.TEXT_PLAIN, new Pair[] {});    
      assertEquals("Data Sent!", result.getResponse().trim());
    	      System.out.println("Result of 'testpostList': " + result.getResponse().trim());
        
      
    } catch (Exception e) {
      e.printStackTrace();
      fail("Exception: " + e);
    }
  }


  /**
   * 
   * Test for the getData method.
   * 
   */
  
  @Test
  public void testgetData() {
    MiniClient c = new MiniClient();
    c.setAddressPort(HTTP_ADDRESS, HTTP_PORT);
    try {
      String DataContent = "initialized";
      c.setLogin(Long.toString(testAgent.getId()), testPass);
      @SuppressWarnings("unchecked")
      ClientResponse result = c.sendRequest("GET", mainPath + "/ ", DataContent,
        MediaType.TEXT_PLAIN, MediaType.TEXT_PLAIN, new Pair[] {});
      assertTrue(true); // change here
      System.out.println("Result of 'testgetData': " + result.getResponse().trim());
    } catch (Exception e) {
      e.printStackTrace();
      fail("Exception: " + e);
    }
  }
  
  /**
   * 
   * Test for the deleteList method.
   * 
   */
  @Test
  public void testdeleteList() {
    MiniClient c = new MiniClient();
    c.setAddressPort(HTTP_ADDRESS, HTTP_PORT);
    try {
      String DeleteContent = "initialized";
      c.setLogin(Long.toString(testAgent.getId()), testPass);
      @SuppressWarnings("unchecked")
      ClientResponse result = c.sendRequest("DELETE", mainPath + "/", DeleteContent,
        MediaType.TEXT_PLAIN, MediaType.TEXT_PLAIN, new Pair[] {});
      assertEquals("Data Deleted!", result.getResponse().trim());
      System.out.println("Result of 'testdeleteList': " + result.getResponse().trim());
    } catch (Exception e) {
      e.printStackTrace();
      fail("Exception: " + e);
    }
  }
  /**
   * 
   * Test for the updateData method.
   * 
   */
  /*
  
  @Test
  public void testupdateData() {
    MiniClient c = new MiniClient();
    c.setAddressPort(HTTP_ADDRESS, HTTP_PORT);
    try {
      String UpdateContent = "caption_update";
      UpdateContent +=  ';' + "message_update" ;
      UpdateContent +=  ';' + "76" ;
      c.setLogin(Long.toString(testAgent.getId()), testPass);
      @SuppressWarnings("unchecked")
      ClientResponse result = c.sendRequest("PUT", mainPath + "/{id}", UpdateContent,
        MediaType.TEXT_PLAIN, MediaType.TEXT_PLAIN, new Pair[] {});
      assertEquals("Message Updated!", result.getResponse().trim());
      System.out.println("Result of 'testupdateData': " + result.getResponse().trim());
    } catch (Exception e) {
      e.printStackTrace();
      fail("Exception: " + e);
    }
  }
  
  */

  /**
   * 
   * Test the ToDoList Microservice Sample for valid rest mapping. Important for development.
   * 
   */
  @Test
  public void testDebugMapping() {
    ToDoList cl = new ToDoList();
    String XML_LOCATION = "./restMapping.xml";
    String xml = cl.getRESTMapping();
  
    try {
      RESTMapper.writeFile(XML_LOCATION, xml);
    } catch (IOException e) {
      e.printStackTrace();
    }
    XMLCheck validator = new XMLCheck();
    ValidationResult result = validator.validate(xml);
    if (!result.isValid()) {
      fail();
    }
  }


  /**
   * 
   * Called after the tests have finished. Shuts down the server and prints out the connector log
   * file for reference.
   * 
   * @throws Exception
   * 
   */
  @AfterClass
  public static void shutDownServer() throws Exception {

    connector.stop();
    node.shutDown();

    connector = null;
    node = null;

    LocalNode.reset();

    System.out.println("Connector-Log:");
    System.out.println("--------------");

    System.out.println(logStream.toString());

  }

}
